
project_id = "kfqorqjwbkxzrqhuvnyh"

[auth]
site_url = "https://www.ipartybrasil.com"
additional_redirect_urls = ["https://www.ipartybrasil.com", "https://kfqorqjwbkxzrqhuvnyh.supabase.co"]

[auth.email]
enable_signup = true
enable_confirmations = true

[functions.send-password-reset-email]
verify_jwt = false

[functions.vendor-approval]
verify_jwt = false

[functions.delete_space_with_photos]
verify_jwt = false

[functions.delete_space_with_notification]
verify_jwt = false

[functions.delete_vendor_with_notification]
verify_jwt = false

[functions.send-deletion-notification]
verify_jwt = false

[functions.send-report]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = false
