
project_id = "kfqorqjwbkxzrqhuvnyh"

[auth]
site_url = "https://www.ipartybrasil.com"
additional_redirect_urls = ["https://www.ipartybrasil.com", "https://kfqorqjwbkxzrqhuvnyh.supabase.co"]

[auth.email]
enable_signup = true
enable_confirmations = true
template = { confirmation = { subject = "Confirme seu email - iParty" } }

[auth.email.smtp]
host = "smtppro.zoho.com"
port = 465
user = "suporte@ipartybrasil.com"
admin_email = "suporte@ipartybrasil.com"
sender_name = "Suporte iParty"

[auth.rate_limits]
signup = { max_frequency = "unlimited" }
password_reset = { max_frequency = "unlimited" }
email_verification = { max_frequency = "unlimited" }

[functions.vendor-approval]
verify_jwt = false

[functions.delete_space_with_photos]
verify_jwt = false

[functions.delete_space_with_notification]
verify_jwt = false

[functions.delete_vendor_with_notification]
verify_jwt = false

[functions.send-deletion-notification]
verify_jwt = false

[functions.send-report]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-email]
verify_jwt = false
