
project_id = "kfqorqjwbkxzrqhuvnyh"

[functions]
[functions.process-payment]
verify_jwt = false
[functions.get-mercado-pago-public-key]
verify_jwt = false
[functions.geocode-address]
verify_jwt = false
