
project_id = "kfqorqjwbkxzrqhuvnyh"

[functions.get_user_by_email]
verify_jwt = true

[functions.get_user_id_by_email]
verify_jwt = true

[functions.check_user_role]
verify_jwt = true

[functions.has_role]
verify_jwt = true

[functions.delete_space_with_photos]
verify_jwt = true

[functions.get_chat_by_users_and_space]
verify_jwt = true

[functions.get_user_chats]
verify_jwt = true
